apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: shartan-ingress
  namespace: shartan
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - shartan.do.houseofmoran.io
        - shartan.houseofmoran.com
      secretName: shartan-cert-prod
  rules:
    - host: shartan.do.houseofmoran.io
      http: &http
        paths:
          - path: /
            backend:
              serviceName: shartan-view-service
              servicePort: 80
    - host: shartan.houseofmoran.com
      http: *http
